include:
  - project: "custom-d/ci-templates"
    file: "Semver.gitlab-ci.yml"


test:php8:
  image: dockerwest/php-laravel:8.0
  script:
    - composer install
    - php vendor/bin/phpunit --colors
    - php vendor/bin/larastan

test:php8:
  image: dockerwest/php-laravel:8.1
  script:
    - composer install
    - php vendor/bin/phpunit --colors
    - php vendor/bin/larastan