name: eloquent-async
recipe: lamp
config:
  via: "cli"
  php: "8.2"

services:

  # php83:
  #   type: php:8.3
  #   via: "cli"

  php81:
    type: php:8.1
    via: "cli"


tooling:
  cleanup:
    cmd: rm -rf vendor composer.lock

  setup81:
    service: php81
    cmd: rm -rf vendor composer.lock && composer install

  setup82:
    service: php82
    cmd: rm -rf vendor composer.lock && composer install

  setup83:
    service: appserver
    cmd: rm -rf vendor composer.lock && composer install


  test81:
    service: php81
    cmd: composer phpunit
  test82:
    service: php82
    cmd: composer phpunit
  test83:
    service: appserver
    cmd: composer phpunit

  stan83:
    service: appserver
    cmd: composer phpstan
  stan82:
    service: php82
    cmd: composer phpstan
  stan81:
    service: php81
    cmd: composer phpstan

  all83:
    service: appserver
    cmd:
      - rm -rf vendor composer.lock && composer install
      - composer phpunit
      - composer phpstan

  all82:
    service: php82
    cmd:
      - rm -rf vendor composer.lock && composer install
      - composer phpunit
      - composer phpstan

  all81:
    service: php81
    cmd:
      - rm -rf vendor composer.lock && composer install
      - composer phpunit
      - composer phpstan


  lara11:
    service: php83
    cmd:
      - rm -rf vendor composer.lock
      - composer require laravel/laravel:^11
      - composer install
      - composer phpunit
      - composer phpstan
      # this is for removing a specific version
      - composer remove laravel/laravel

  lara10:
    service: php82
    cmd:
      - rm -rf vendor composer.lock
      - composer require laravel/laravel:^10
      - composer install
      - composer phpunit
      - composer phpstan
      # this is for removing a specific version
      - composer remove laravel/laravel

  lara9:
    service: php81
    cmd:
      - rm -rf vendor composer.lock
      - composer require laravel/laravel:^9
      - composer install
      - composer phpunit
      - composer phpstan
      # this is for removing a specific version
      - composer remove laravel/laravel
