<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0).
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateRsaKeystoreTable extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::create('rsa_keystore', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->text('public_key')->nullable();
            $table->text('private_key')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        Schema::dropIfExists('rsa_keystore');
    }
}
